#!/bin/bash

export PATH=$PATH:./scripts:./Python

# Assume production
export NODE_ENV=production

# Give Python access to traders
export PYTHONPATH=./Python:~/traders:.:$PYTHONPATH

source ./.venv/bin/activate

echo -n "simulator version: ";node -pe "require('./package.json').version"

