#!/bin/bash

# Ensure any existing python environments are deactivated
set -e
conda deactivate >/dev/null 2>&1 || true
deactivate >/dev/null 2>&1 || true
set +e

export PATH=$PATH:./scripts:./Python

# Assume production
export NODE_ENV=production

# Give Python access to traders
export PYTHONPATH=./Python:~/traders:.:$PYTHONPATH

source ./.venv/bin/activate

echo -n "Simulator version: ";node -pe "require('./package.json').version"

