"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const debug_1 = __importDefault(require("debug"));
exports.debugHft = debug_1.default('hft');
exports.debugBuy = debug_1.default('buy');
exports.debugBuyDetail = debug_1.default('buydetail');
exports.debugSell = debug_1.default('sell');
exports.debugCancel = debug_1.default('cancel');
exports.debugSellDetail = debug_1.default('selldetail');
exports.debugCycle = debug_1.default('cycle');
exports.debugHttp = debug_1.default('http');
exports.debugRaw = debug_1.default('raw');
exports.debugOrder = debug_1.default('order');
exports.debugOrderDetail = debug_1.default('orderdetail');
exports.debugBalance = debug_1.default('balance');
exports.debugMessage = debug_1.default('message');
exports.debugDestructure = debug_1.default('destructure');
exports.debugOrderbook = debug_1.default('orderbook');
exports.debugArchive = debug_1.default('archive');
exports.debugRateLimited = debug_1.default('ratelimited');
exports.debugCO = debug_1.default('co');
exports.debugBroker = debug_1.default('broker');
exports.debugException = debug_1.default('exception');
exports.debugTrace = debug_1.default('trace');
exports.debugBackstop = debug_1.default('backstop');
exports.debugSignalR = debug_1.default('signalr');
exports.debugTrade = debug_1.default('trade');
exports.debugMap = new Map();
