#!/usr/bin/env python

import os
import sys
from pymongo import MongoClient
from bson.objectid import ObjectId
import logging


if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)

    assert os.environ['MONGODB'], 'MONGODB Not Defined'
    local_client = MongoClient('127.0.0.1:27017')

    history_db = local_client.history

    collections = [
        history_db.orderbooks,
    ]

    print('Delete All Local Documents')

    for collection in collections:
        collection.delete_many({})

    print("That's All Folks")
