#!/usr/bin/env python

import os
import sys
from pymongo import MongoClient
from bson.objectid import ObjectId
import logging

#@profile
if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)

    assert os.environ['MONGODB'], 'MONGODB Not Defined'
    remote_mongo_client = MongoClient(os.environ['MONGODB'])

    db = os.environ['SIMULATOR_DB']
    assert db, 'SIMULATOR_DB Not Defined'
    sim_db = remote_mongo_client[db]

    sim_collections = [
        sim_db.runs,
        sim_db.partitions,
        sim_db.trades,
        sim_db.simulations,
        sim_db.matchings,
        sim_db.orderbooks,
    ]

    if db == 'sim_dev' and len(sys.argv) == 1:

        print('Delete All Historical Simulator Documents')

        for collection in sim_collections:
            collection.delete_many({})

        print("That's All Folks")


    elif len(sys.argv) == 2:

        runId = sys.argv[1]

        for collection in sim_collections:

            collection.delete_many(filter = {"runId": ObjectId(runId)})

        print (f"Simulator Run {runId} Removed")

    else:

        print("Usage: 'clean <runId>'")
        exit(0)

    exit(0)
