#!/bin/bash

export PATH=$PATH:./scripts:./Python

# Assume production
export NODE_ENV=production

# Various useful functions
source ./scripts/bash-functions

# Various useful aliases
source ./scripts/aliases

# Give Python access to traders
export PYTHONPATH=~/traders:.:$PYTHONPATH

# Some pytest options
# export PYTEST_ADDOPTS="--benchmark-columns=Mean,Median,Rounds"

source ./bin/activate

# export the version
source ./scripts/software.version
