#!/bin/bash

export PATH=$PATH:./scripts:./Python

# Assume production
export NODE_ENV=production

# Various useful functions
source ./scripts/bash-functions

# Various useful aliases
source ./scripts/aliases

# Give Python access to traders
export PYTHONPATH=$SIMULATOR_PATH/Python:~/traders:.:..:$PYTHONPATH

source ./bin/activate

# export the version
source ./scripts/software.version
