#!/bin/bash
PROGNAME=$(basename $0)

# Various useful functions
source ./scripts/bash-functions

# Various useful aliases
source ./scripts/aliases

# Ensure all is freshly transpiled
tsc
if [ $? -ne 0 ]; then echo $PROGNAME' Aborted'; exit 1; fi

# export the version
source ./scripts/software.version

git add .
if [ $? -ne 0 ]; then echo $PROGNAME' Aborted'; exit 1; fi

git commit -m ${SIM_VERSION:1}
if [ $? -ne 0 ]; then echo $PROGNAME' Aborted'; exit 1; fi

git push origin $(get_current_branch)
if [ $? -ne 0 ]; then echo $PROGNAME' Aborted'; exit 1; fi

# Tag the Version
git tag --list | egrep ${SIM_VERSION:1}
if [ $? -eq 0 ]; then
    tag-mv ${SIM_VERSION:1}
    if [ $? -ne 0 ]; then echo $PROGNAME' Aborted'; exit 1; fi
else
    tag-add ${SIM_VERSION:1}
    if [ $? -ne 0 ]; then echo $PROGNAME' Aborted'; exit 1; fi
fi

echo $PROGNAME' Complete'
exit 0
